import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { signIn, signOut, useSession, getSession } from "next-auth/client";

export default function Home() {
  const [session, loading] = useSession();
  console.log("session: ", session);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <iframe src="/api/jwt" />
        {!session && (
          <>
            Not signed in <br />
            <button
              onClick={() =>
                signIn(null, { callbackUrl: "http://localhost:3000/happy" })
              }
            >
              Sign in
            </button>
          </>
        )}
        {session && (
          <>
            Signed in <br />
            <button
              onClick={() =>
                signOut(null, { callbackUrl: "http://localhost:3000" })
              }
            >
              Sign out
            </button>
          </>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
